repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: venv
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.1.0
    hooks:
      - id: flake8
        exclude: venv
