ci:
  autofix_commit_msg: "fix: [pre-commit.ci] fix validation errors"
  autoupdate_commit_msg: "ci: [pre-commit.ci] autoupdate"

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        files: services/consumer/pyproject.toml

  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
        args: [--verbose]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--filter-files"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: name-tests-test
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: .devcontainer/devcontainer.json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        args: ["-x", "*_test.py"]

  - repo: https://github.com/myint/autoflake
    rev: "v1.7.7"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --expand-star-imports
          - --ignore-init-module-imports

  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E501

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.19.2"
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
